version: "3.9"

services:
  db:
    image: postgres
    ports:
       - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  web:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    links:
      - db

